# coding: utf-8

"""
    LOCKSS Repository Service REST API

    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501

    OpenAPI spec version: 1.9
    Contact: dlvargas@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_repository
from lockss_repository.api.collections_api import CollectionsApi  # noqa: E501
from lockss_repository.rest import ApiException


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = lockss_repository.api.collections_api.CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collections_collectionid_artifacts_artifactid_delete(self):
        """Test case for collections_collectionid_artifacts_artifactid_delete

        Remove an artifact from the repository  # noqa: E501
        """
        pass

    def test_collections_collectionid_artifacts_artifactid_get(self):
        """Test case for collections_collectionid_artifacts_artifactid_get

        Get artifact content and metadata  # noqa: E501
        """
        pass

    def test_collections_collectionid_artifacts_artifactid_put(self):
        """Test case for collections_collectionid_artifacts_artifactid_put

        Update the committed property of an artifact  # noqa: E501
        """
        pass

    def test_collections_collectionid_artifacts_post(self):
        """Test case for collections_collectionid_artifacts_post

        Create an artifact  # noqa: E501
        """
        pass

    def test_collections_collectionid_aus_auid_artifacts_get(self):
        """Test case for collections_collectionid_aus_auid_artifacts_get

        Get committed artifacts in a collection and Archival Unit  # noqa: E501
        """
        pass

    def test_collections_collectionid_aus_auid_size_get(self):
        """Test case for collections_collectionid_aus_auid_size_get

        Get the size of Archival Unit artifacts in a collection  # noqa: E501
        """
        pass

    def test_collections_collectionid_aus_get(self):
        """Test case for collections_collectionid_aus_get

        Get Archival Unit IDs (AUIDs) in a collection  # noqa: E501
        """
        pass

    def test_collections_get(self):
        """Test case for collections_get

        Get collection identifiers of the committed artifacts in the repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
