# coding: utf-8

"""
    LOCKSS RepositoryService API

    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dlvargas@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_repository
from lockss_repository.models.streaming_response_body import StreamingResponseBody  # noqa: E501
from lockss_repository.rest import ApiException


class TestStreamingResponseBody(unittest.TestCase):
    """StreamingResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamingResponseBody(self):
        """Test StreamingResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_repository.models.streaming_response_body.StreamingResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
