# coding: utf-8

"""
    LOCKSS Repository Service REST API

    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501

    OpenAPI spec version: 1.9
    Contact: dlvargas@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "lockss-repository-python"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="LOCKSS Repository Service REST API",
    author_email="dlvargas@stanford.edu",
    url="https://github.com/lockss/lockss-repository-python",
    keywords=["Swagger", "LOCKSS Repository Service REST API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501
    """
)
