# coding: utf-8

"""
    LOCKSS RepositoryService API

    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dlvargas@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Artifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'collection': 'str',
        'auid': 'str',
        'uri': 'str',
        'version': 'int',
        'committed': 'bool',
        'storage_url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'collection': 'collection',
        'auid': 'auid',
        'uri': 'uri',
        'version': 'version',
        'committed': 'committed',
        'storage_url': 'storageUrl'
    }

    def __init__(self, id=None, collection=None, auid=None, uri=None, version=None, committed=None, storage_url=None):  # noqa: E501
        """Artifact - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._collection = None
        self._auid = None
        self._uri = None
        self._version = None
        self._committed = None
        self._storage_url = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if collection is not None:
            self.collection = collection
        if auid is not None:
            self.auid = auid
        if uri is not None:
            self.uri = uri
        if version is not None:
            self.version = version
        if committed is not None:
            self.committed = committed
        if storage_url is not None:
            self.storage_url = storage_url

    @property
    def id(self):
        """Gets the id of this Artifact.  # noqa: E501


        :return: The id of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Artifact.


        :param id: The id of this Artifact.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def collection(self):
        """Gets the collection of this Artifact.  # noqa: E501


        :return: The collection of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._collection

    @collection.setter
    def collection(self, collection):
        """Sets the collection of this Artifact.


        :param collection: The collection of this Artifact.  # noqa: E501
        :type: str
        """

        self._collection = collection

    @property
    def auid(self):
        """Gets the auid of this Artifact.  # noqa: E501


        :return: The auid of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._auid

    @auid.setter
    def auid(self, auid):
        """Sets the auid of this Artifact.


        :param auid: The auid of this Artifact.  # noqa: E501
        :type: str
        """

        self._auid = auid

    @property
    def uri(self):
        """Gets the uri of this Artifact.  # noqa: E501


        :return: The uri of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this Artifact.


        :param uri: The uri of this Artifact.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def version(self):
        """Gets the version of this Artifact.  # noqa: E501


        :return: The version of this Artifact.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Artifact.


        :param version: The version of this Artifact.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def committed(self):
        """Gets the committed of this Artifact.  # noqa: E501


        :return: The committed of this Artifact.  # noqa: E501
        :rtype: bool
        """
        return self._committed

    @committed.setter
    def committed(self, committed):
        """Sets the committed of this Artifact.


        :param committed: The committed of this Artifact.  # noqa: E501
        :type: bool
        """

        self._committed = committed

    @property
    def storage_url(self):
        """Gets the storage_url of this Artifact.  # noqa: E501


        :return: The storage_url of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._storage_url

    @storage_url.setter
    def storage_url(self, storage_url):
        """Sets the storage_url of this Artifact.


        :param storage_url: The storage_url of this Artifact.  # noqa: E501
        :type: str
        """

        self._storage_url = storage_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Artifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Artifact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
