# coding: utf-8

# flake8: noqa
"""
    LOCKSS Repository Service REST API

    API of the LOCKSS RepositoryService for the LAAWS project  # noqa: E501

    OpenAPI spec version: 1.9
    Contact: dlvargas@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from lockss_repository.lockss-repository-python.artifact import Artifact
from lockss_repository.lockss-repository-python.streaming_response_body import StreamingResponseBody
